### PR TITLE
Suppress gerritadmin entirely

### PR DESCRIPTION
**Pull request by Krenair**
Per issue #7, all the channels that this bot is in have grrrit-wm. It doesn't make much sense to forward anything from gerritadmin there.

### CODE REVIEW

**Comment by valhallasw** [comment]
I'm not completely sure about that -- grrrrt-wm doesn't show the relevant bugzilla URL in the change, as far as I know, and this is useful for e.g. closing the bug or leaving a comment there.

**Comment by yuvipanda** [comment]
We should probably fix that by having the gerritadmin bot recognize a
'Closes: <BugNumber>' that also closes it.

On Thu, Apr 24, 2014 at 1:38 PM, Merlijn van Deen
notifications@github.comwrote:

> I'm not completely sure about that -- grrrrt-wm doesn't show the relevant
> bugzilla URL in the change, as far as I know, and this is useful for e.g.
> closing the bug or leaving a comment there.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/valhallasw/pywikibugs/pull/9#issuecomment-41253897
> .

## 

Yuvi Panda T
http://yuvi.in/blog

**Comment by Krinkle** [comment]
@yuvipanda I think that's an unfair justification. You're saying it's useful to have wikibugs leave another message in the channel, repeating what grrrrt-wm said in the previous message (change created, merged or abandoned), just for the sake of having a link to the bugzilla url?

The relevant bugzilla page is already linked from the Gerrit change page, which is linked to already. In the commit message is a, fully linkified, pointer to bugzilla ([`Bug: 12345`](https://bugzilla.wikimedia.org/12345)). That's the reason why Gerrit was able to notify bugzilla in the first place.

Maybe reduce wikibugs' message to just "Gerrit change 129844 references bug 12345: https://bugzilla.wikimedia.org/12345"

So instead of:

> - grrrit-wm: (Merged) jenkins-bot: Obey specified behaviour and allow Param#deprecated to be boolean true [extensions/TemplateData] - https://gerrit.wikimedia.org/r/129844 (owner: Trevor Parscal)
> - wikibugs: MediaWiki extensions / TemplateData: TemplateData: Make description for Param#deprecated optional - https://bugzilla.wikimedia.org/53412#c2 (Gerrit Notification Bot) Change 129844 merged by jenkins-bot: Obey specified behaviour and allow Param#deprecated to be boolean true  https://gerrit.wikimedia.org...

I'd be:

> - grrrit-wm: (Merged) jenkins-bot: Obey specified behaviour and allow Param#deprecated to be boolean true [extensions/TemplateData] - https://gerrit.wikimedia.org/r/129844 (owner: Trevor Parscal)
> - wikibugs: Gerrit change 129844 references bug 53412: https://bugzilla.wikimedia.org/53412

I mean, literally all other words in the message are either duplicated or not useful in general. Except maybe the bug title, though I'd leave it out as the user interested in clicking the bugzilla link will probably decide clicking it regardless of the bug title and instead based on the other factors.

**Comment by valhallasw** [comment]
I think the different message option is reasonable. I'm also OK with merging this change for #wikimedia-dev (i.e. using it as a filter in the channel dict), but at least in #pywikipediabot, I enjoy having bugzilla URLs posted.

**Comment by yuvipanda** [comment]
@Krinkle You were probably replying to @valhallasw, not me :)
So, as of https://gerrit.wikimedia.org/r/#/c/129945/ (which is now merged and deployed), grrrit-wm also displays the bug link in its messages if there is one. I think we can suppress gerritadmin now?

**Comment by yuvipanda** [comment]
Going to do the BEBOLD thing and merge / deploy this.

**Pull request merged**
